### ISSUE TITLE
一个结果的问题

### ISSUE THREAD

**Issue by zhangwenda0518** [JiangLab2020/PUGTA#1]
作者，您好，请允许我使用中文提问。
我正在研究我的一个非模式的植物物种的糖基转移酶，我使用了Gmind方法进行预测并得到202个UGT注释，对结果的输出，我有些疑问，结果文件中cds和pep序列名可以解释下吗(红色绿色部分)？为什么两个后面的信息不一致？txt结尾文件的输出，是用来过滤阈值的嘛？
![image](https://github.com/user-attachments/assets/251de7eb-3644-4242-90e8-1338a86b114f)

我想知道哪部分是序列的位置呢，我想与已注释的基因组结果进行比较。

此外怎么生成gff3的注释结果呢，可以添加这个功能嘛。

谢谢您！

**Comment by liuyuqian2050** [comment]
您好，
感谢您的提问，回复如下：
1、GMind方法首先从基因组上取出可能包含UGTs的片段（红色部分），再对该片段用多种方法注释基因，绿色表示对于前述基因片段（红色部分）相对位置，通过计算可得该基因的位置（pep文件标注）。cds文件与pep文件的位置计算后是一致的（13091287+75325-1=13166611; 13091287+76671-1=13167957）。
2、txt文件表示评估过程中打分，用于蛋白过滤，该文件表示过滤后的蛋白打分，仅作参考。
